name: rectangles
version: 0.0.1
description: >-
  Simple implementation of rectangles and points
author: Peter Loos <peter.loos@gmx.de>
homepage: http://peterloos.de
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
